# Generated by Django 3.2.23 on 2024-01-02 19:26

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggapp', '0005_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('item_price', models.FloatField()),
                ('item_description', models.TextField(max_length=200)),
                ('item_catagory', models.CharField(max_length=200)),
                ('item_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.DeleteModel(
            name='item',
        ),
    ]
