# Generated by Django 3.2.23 on 2024-01-02 21:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('veggapp', '0007_auto_20240102_2056'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='UserComments',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='UserPost',
        ),
    ]
