# Generated by Django 3.2.23 on 2024-01-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggapp', '0008_auto_20240102_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
