# Generated by Django 3.2.23 on 2024-01-03 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veggapp', '0010_userpost_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='excerpt',
        ),
    ]
