# Generated by Django 3.2.23 on 2024-01-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggapp', '0014_auto_20240115_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
