# Generated by Django 3.2.23 on 2024-01-15 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggapp', '0015_alter_userpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
