# Generated by Django 3.2.23 on 2024-01-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggapp', '0016_alter_userpost_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpost',
            name='content',
        ),
        migrations.AddField(
            model_name='userpost',
            name='excerpt',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
